name: Development pipeline

on:
  push:
    branches:
      - "beta"
      - "ptr"
      - "master"
  workflow_dispatch:     

jobs:
  release:
    name: Publish development build to github
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.KEY }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Workaround checkout issues
        run: |
          git fetch --tags --force
      - name: Create Package
        uses: BigWigsMods/packager@v2
        with:
          args: -n "{package-name}-{project-version}"
      - name: Get package name
        run: | 
          echo "PACKAGE=$(find .release -type f -name *.zip -printf "%f\n")" >> $GITHUB_ENV
          echo "VER=$(echo "${{ env.PACKAGE }}" | sed -E 's/.*-(v[0-9]{2}\.[0-9]{2}).+([a-zA-Z0-9]{8})\.zip/\1-\2/')" >> $GITHUB_ENV  
      - name: rename
        run: | 
          mv ".release/${{ env.PACKAGE }}" ".release/ElvUI-${{ env.VER }}.zip"         
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ".release/ElvUI-${{ env.VER }}.zip" 
          tag: ${{ env.VER }}
          commit: "beta"    
